### PR TITLE
vshare.eu tls fix

### PR DESCRIPTION
**Pull request by siriuzwhite**

### CODE REVIEW

**Comment by QDaniel** [comment]
Can you send a movie name with vshare hoster?
The tls of vshare is ok there are no need for a tls exception

**Comment by siriuzwhite** [comment]
I tested with "The Flash" Season 4 Episode 23 (german version)
In the current state a SSLHandshakeException will be raised.

**Comment by QDaniel** [comment]
I have tested with two devices. No SSL problems.

Have you the same issue when you  open it in the Android internal browser? Can you post the wrong certificate?

I have at vshare a cerificate from Lets Encrypt

**Comment by siriuzwhite** [comment]
Yes they use a Lets Encrypt Certificate but it seems they didn't implemented it on their server correctly, because there are chain issues that produce errors on some systems. Have a look at: https://www.ssllabs.com/ssltest/analyze.html?d=vshare.eu

On my Fire OS 5.3.6.4 I get the following exception while debugging:
`W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:322)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:212)
        at com.android.okhttp.Connection.connect(Connection.java:166)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:323)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:238)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:124)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:563)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:540)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:227)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:216)
        at com.ov3rk1ll.kinocast.api.mirror.VShare.getVideoPath(VShare.java:55)
        at com.ov3rk1ll.kinocast.ui.DetailActivity$QueryPlayTask.doInBackground(DetailActivity.java:612)
        at com.ov3rk1ll.kinocast.ui.DetailActivity$QueryPlayTask.doInBackground(DetailActivity.java:552)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:331)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:232)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:114)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
    	... 21 more
    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err: 	... 27 more`

**Comment by QDaniel** [comment]
I will add a setting in the preferences.

**Comment by QDaniel** [comment]
Closed by b0a95075a5420f58dec1ce3e0384c394e7b8db1b

**Pull request closed without merging**
